# makefile which automatically adapts to new files in src
# also uses file compilation dependencies generated by the compiler for minimal partial rebuilds

# binary name
BIN=a.out
BUILD_DIR=build

# uncomment next assignment for a release build
RELEASE=#-DNDEBUG

# general compiler flags
CXX=g++
CXXFLAGS=-g -std=c++20 #-shared -fPIC
DEPFLAGS=-MT $@ -MMD -MF $(patsubst $(BUILD_DIR)/$(BUILD_OBJ_DIR)/%.o, $(BUILD_DIR)/$(BUILD_DEP_DIR)/%.d, $@)
WARNINGS=-Wall -Wextra -Wshadow -pedantic -Wstrict-aliasing #-Wfloat-conversion -Wconversion -Warith-conversion -Wfloat-equal -Wold-style-cast
OPTIMIZATIONS=-O3 #-march=native -mtune=native -mfma -mavx2 -ftree-vectorize -ffast-math
LIBS=-lSDL2 -lSDL2_ttf
INCL=-Isrc/
CORES=20

# set-up build directories
SRC_FOLDERS=$(patsubst %, %/, $(shell find src -type d -print))
SRC_FILES=$(wildcard $(patsubst src%/, src%/*.hpp, $(SRC_FOLDERS))) $(wildcard $(patsubst src%/, src%/*.cpp, $(SRC_FOLDERS)))
TMP_FILE_DIR=tmp
BUILD_OBJ_DIR=$(TMP_FILE_DIR)/obj
BUILD_DEP_DIR=$(TMP_FILE_DIR)/dep
BUILD_SUBDIRS=$(patsubst src%/, $(BUILD_DIR)/$(BUILD_OBJ_DIR)%/, $(SRC_FOLDERS)) $(patsubst src%/, $(BUILD_DIR)/$(BUILD_DEP_DIR)%/, $(SRC_FOLDERS)) $(BUILD_DIR)/$(BUILD_HEADER_DIR)

# objects to compile
# create an .o file for every .cpp file
ALL_OBJ=$(patsubst src/%.cpp, $(BUILD_DIR)/$(BUILD_OBJ_DIR)/%.o, $(wildcard $(patsubst src%/, src%/*.cpp, $(SRC_FOLDERS))))
# .o files which should not be created (.cpp which should not be compiled)
FILTER_OBJ=
OBJ=$(filter-out $(FILTER_OBJ), $(ALL_OBJ))

.PHONY: all sanitize force fresh clean valgrind lines trailing_spaces help


all:
	# compile src
	make -j $(CORES) $(BUILD_DIR)/$(BIN) --no-print-directory

	# copy resource dir
	cp -r -u rsc $(BUILD_DIR)/

	@# clean compilation files when building release
	@if [ "$(RELEASE)" != "" ]; then \
		echo "# cleaning build files..."; \
		echo "rm -rf $(BUILD_DIR)/$(TMP_FILE_DIR)"; \
		rm -rf $(BUILD_DIR)/$(TMP_FILE_DIR); \
	fi


sanitize:
	make BUILD_DIR=$(BUILD_DIR)_asan CXXFLAGS="$(CXXFLAGS) -fsanitize=address" --no-print-directory


force:
	make -B all --no-print-directory


fresh:
	make clean --no-print-directory
	make all --no-print-directory


clean:
	rm -rf $(BUILD_DIR)
	rm -rf $(BUILD_DIR)_asan


# binary rule
$(BUILD_DIR)/$(BIN): $(OBJ)
	$(CXX) $(CXXFLAGS) $(WARNINGS) $(OPTIMIZATIONS) -o $@ $^ $(LIBS)


# the different build folders needed
$(BUILD_SUBDIRS):
	mkdir -p $@


# object file rule. Also makes dependency files using $(DEPFLAGS)
$(BUILD_DIR)/$(BUILD_OBJ_DIR)/%.o: src/%.cpp | $(BUILD_SUBDIRS)
	$(CXX) $(DEPFLAGS) $(CXXFLAGS) $(RELEASE) $(INCL) $(WARNINGS) $(OPTIMIZATIONS) -c $< -o $@


# include the dependencies
include $(wildcard $(patsubst $(BUILD_DIR)/$(BUILD_OBJ_DIR)/%.o, $(BUILD_DIR)/$(BUILD_DEP_DIR)/%.d, $(OBJ)))


valgrind: all
	clear
	valgrind --leak-check=full --error-limit=no $(BUILD_DIR)/$(BIN)  #--show-reachable=yes


lines:
	wc -l $(SRC_FILES)


# note that when copy pasting the grep command, the extra $ has to be removed
trailing_spaces:
	@grep --color=auto -n -r '[[:blank:]]$$' -r src/ Makefile || echo -e "No trailing spaces in source!\n"


help:
	@echo The default build target is \"all\", produces the build in $(BUILD_DIR).
	@echo \"make clean\" removes all built files.
	@echo \"make force\" forces all build targets to be rebuild.
	@echo \"make fresh\" runs \"make clean\; make\", which may help with potential building problems after updating.
	@echo \"make sanitize\" builds with -fsanitize=address. Do not forget to run \"make force\" to remove sanitize.
	@echo
	@echo Furthermore, some often used command are added to the makefile:
	@echo \"make lines\" counts the number of lines in all source files.
	@echo \"make trailing_spaces\" searches all source files for trailing whitespace characters \(whitespace characters before line end\).
